name: deploy-expiration

on:
  push:
    branches:
      - master
    paths:
      - "expiration/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd expiration && docker build -t 29ff/ticketapp-expiration .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push 29ff/ticketapp-expiration
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.PROVIDER_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketapp
      - run: kubectl rollout restart deployment expiration-depl
